// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wypwqevgbtusiayyjrpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5cHdxZXZnYnR1c2lheXlqcnBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NDMxMTgsImV4cCI6MjA3MDQxOTExOH0.GPmR7YSxQJuvnMqlzGWehE_pKhc6QoDLLkwpnC4Zm7k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});